[project]
name = "EX09"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "packaging>=26.1",
    "pandas>=2.3.3",
    "jupyter>=1.1.1",
    "langchain>=1.2.15",
    "pyarrow>=24.0.0",
    "matplotlib>=3.10.8",
    "pydantic>=2.13.3",
    "langchain-ollama>=1.1.0",
    "langgraph>=1.1.10",
    "langchain-community>=0.4.1",
    "huggingface-hub[cli]>=0.36.2",
    "torch",
    "transformers",
    "peft",
    "trl",
    "bitsandbytes",
    "datasets",
    "accelerate",
]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu126" }
torchvision = { index = "pytorch-cu126" }